### ISSUE TITLE
excuse me,I would like to know when the code will be updated

### ISSUE THREAD

**Issue by Kitzzaaa** [as791/ZOO_Attack_PyTorch#5]

**Comment by as791** [comment]
@Kitzzaaa I am not able to test it till now to update the repo. I can share the code with you if you are getting delayed because of this. Please share your mail-id.

**Comment by Kitzzaaa** [comment]
bouposhowvn@gmail.com

**Comment by Kitzzaaa** [comment]
> @Kitzzaaa I am not able to test it till now to update the repo. I can share the code with you if you are getting delayed because of this. Please share your mail-id.

bouposhowvn@gmail.com

**Comment by Kitzzaaa** [comment]
@as791 ,my email is     bouposhowvn@gmail.com
Thank you

**Comment by Kitzzaaa** [comment]
@as791 ,my email is bouposhowvn@gmail.com
Thank you
